config/routes.rb
Rails.application.routes.draw do
  
  resources :regions do
    resources :places
  end
  
  resources :articles
  resources :categories
  resources :users_roles
  resources :roles
  resources :accounts

  get "/home/info" => "home#info", :as => :info
  post "/accounts/set_current_account/:id" => "accounts#set_current_account", :as => :set_current_account
  post "/accounts/set_state/:id" => "accounts#set_state", :as => :set_state
  post "/accounts/apply_account" => "accounts#apply_account", :as => :applyAccount

  root 'home#index'

  devise_for :users, controllers:{ registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :user

	has_many :preferences, :dependent => :destroy
	has_many :categories, through: :preferences

	after_create :save_categories
	after_update :update_categories

	def categories=(value)
		@categories = value
	end

	private

	def save_categories
		if @categories != nil
			@categories.each do |category_id|
				Preference.create(category_id: category_id, account_id: self.id)
			end
		end
	end

	def update_categories
		if @categories != nil
			Preference.where(account_id: self.id).destroy_all
			@categories.each do |category_id|
				Preference.create(category_id: category_id, account_id: self.id)
			end
		end
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	validates :title, presence: true
	validates :body, presence: true
	has_many :has_categories, :dependent => :destroy
	has_many :categories, through: :has_categories
	after_create :save_categories

	has_attached_file :cover #, styles: { large: "900x700", medium: "600x400", thumb: "500x300", small: "300x100" }
		#, :storage => :cloudinary, :path => ':id/:filename', :cloudinary_resource_type => :video
			#, :cloudinary_resource_type => :image 

	validates_attachment_content_type :cover,
		:content_type => ['video/mp4'],
		:message => "Sorry, right now we only support MP4 video",
		:if => :is_type_of_video?
	validates_attachment_content_type :cover,
		:content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'],
		:message => "Different error message",
		:if => :is_type_of_image?

	def categories=(value)
		@categories = value
	end

	protected

	def is_type_of_video?
		cover.content_type =~ %r(video)
	end

	def is_type_of_image?
		cover.content_type =~ %r(image)
	end


	private

	def save_categories
		@categories.each do |category_id|
			HasCategory.create(category_id: category_id, article_id: self.id)
		end
	end

end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true

	has_many :has_categories
	has_many :articles, through: :has_categories

	has_many :preferences
	has_many :accounts, through: :preferences

end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/place.rb
class Place < ApplicationRecord

	belongs_to :region

	has_attached_file :imagen , styles: { large: "900x700", medium: "600x400", thumb: "500x300", small: "300x100" }
	validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/

end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :account
  belongs_to :category
end

app/models/region.rb
class Region < ApplicationRecord
	has_attached_file :imagen , styles: { large: "900x700", medium: "600x400", thumb: "500x300", small: "300x100" }
	validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users_roles
	has_many :users, through: :users_roles

end

app/models/user.rb
class User < ApplicationRecord
	has_many :accounts, :dependent => :destroy
	has_many :users_roles, :dependent => :destroy
	has_many :roles, through: :users_roles

	after_create :set_role

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	def roles=(value)
		@roles = value
	end

	def set_role
		role = Role.find_by_name("subscribed")
		UsersRole.create(role_id: role.id, user_id: self.id)
		Account.create(user_id: self.id, role: role.name, state: "pending", location: "utp")
		UserMailer.notify_account(self).deliver
	end

end

app/models/users_role.rb
class UsersRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = Category.all
    @places = Place.all
  end

  # GET /articles/1/edit
  def edit
    @places = Places.all
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.categories = params[:categories]
    @places = Place.all
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @places = Place.all
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :location, :cover, :categories)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@last_articles ||= []
  	@categories = Category.all
  	@categories.each do |category|
  		@articles = category.articles
  		@last_articles.push(@articles.last)
  	end
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for(flash_type)
  case flash_type
  when "success"
    "alert-success"   # Green
  when "error"
    "alert-danger"    # Red
  when "alert"
    "alert-warning"   # Yellow
  when "notice"
    "alert-info"      # Blue
  else
    flash_type.to_s
  end
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_roles_helper.rb
module UsersRolesHelper
end

app/views/articles/_admin.html.erb
<!--p id="notice"><%= notice %></p-->
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul class="breadcrumb">
        <h1>Artículos</h1>
        <h><%= link_to 'Nuevo artículo', new_article_path %></h>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="scrolling outer">
        <div class="inner">
          <table class="table table-hover table-condensed table-bordered">
          <thead>
            <tr style="font-weight:bold; background:lightgrey">
              <th style="background:lightgrey">Nombre</th>
              <td>Información</td>
              <td>Ubicación</td>
              <td colspan="3"></td>
            </tr>
          </thead>
            <tbody>
              <% @articles.each do |article| %>
                <tr>
                  <th><%= article.title %></th>
                  <td><%= truncate(article.body) %></td>
                  <td><%= article.location %></td>
                  <td><%= link_to 'Ver', article %></td>
                  <td><%= link_to 'Editar', edit_article_path(article) %></td>
                  <td><%= link_to 'Eliminar', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
          </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/articles/_form.html.erb
  <div class="row">
    <div class="col-md-5 col-centered" align="left" style="font-size: 1.1em;">
      <%= bootstrap_form_for(article, local: true) do |f| %>
        <% if article.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

            <ul>
            <% article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.text_field :title, label: "Título", required: true %>
        </div>

        <div class="field">
          <%= f.file_field :cover, label: "Portada", required: true %>
        </div>

        <div class="field">
          <%= f.text_area :body, label: "Descripción", required: true, rows: "8" %>
        </div>

        <div class="field">
          <%= f.select :location, options_for_select(@places.order('nombre ASC').map{ |c| [c.nombre]}), label: "Ubicación", required: true %>
        </div>

        <h2>Categorias</h2>
            <% @categories.each do |category| %>
            <div class="field">
              <%= check_box_tag "categories[]", category.id %> <%= category.name %>
            </div>
            <%end%>
        <br>
        <div class="actions">
          <%= f.submit "Crear artículo", :class => 'btn btn-md btn-primary' %>
        </div>
        <br>
      <% end %>
    </div>
  </div>

app/views/articles/edit.html.erb
<div class="container">
	<h1>Editando artículo</h1>

	<%= render 'form', article: @article %>

	<%= link_to 'Show', @article %> |
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<!--p id="notice"><%= notice %></p-->
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul class="breadcrumb">
        <h1>Artículos</h1>
        <h><%= link_to 'Nuevo artículo', new_article_path %></h>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="scrolling outer">
        <div class="inner">
          <table class="table table-hover table-condensed table-bordered">
            <tr>
              <th>Nombre</th>
              <td>Información</td>
              <td>Ubicación</td>
              <td colspan="3"></td>
            </tr>
            <tbody>
              <% @articles.each do |article| %>
                <tr>
                  <th><%= article.title %></th>
                  <td><%= truncate(article.body) %></td>
                  <td><%= article.location %></td>
                  <td><%= link_to 'Ver', article %></td>
                  <td><%= link_to 'Editar', edit_article_path(article) %></td>
                  <td><%= link_to 'Eliminar', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
          </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/articles/new.html.erb
<div class="container">
	<h1>Nuevo artículo</h1>

	<%= render 'form', article: @article %>

	<%= link_to 'Atras', :back %>
</div>

app/views/articles/show.html.erb
<!--p id="notice"><%= notice %></p-->
<div class="container">
 <!-- Project One -->
    <div class="row">
        <div class="col-md-5">
        <%= @article.cover.content_type %>
        <% if @article.cover.content_type == 'video/mp4' || @article.cover.content_type == 'application/octet-stream' %>
           	<%= video_tag @article.cover.url(), class: "img-responsive", controls: true %>
        <% else %>
        	<%= image_tag @article.cover.url(), class: "img-responsive" %>
        <%end%>

        </div>
        <div class="col-md-5 ">
	        <ul class="breadcrumb">
	            <h3 style="color:black"><%= @article.title %></h3>
	            <h>Ubicación:  <%= @article.location %></h>
	            <br>
	            <h>Categorias: </h>
	        	<% @article.categories.each do |category| %>
	        		<%= link_to category.name, category%>
	        	<%end%>
	        </ul>
	            <textarea disabled style="color:black" class="form-control"><%= @article.body %></textarea>
	            <br>
	            <a class="btn btn-primary" href="#">Me gusta! <span class="glyphicon glyphicon-thumbs-up"></span>
	            </a>
	        <div class="row-md-3">
	        	<br>
	        	<% if current_account.role == "admin" %>
		           <% link_to 'Editar artículo', edit_article_path(@article) %>
						<% link_to 'Artículos', accounts_path %>
				<%end%>
				<br>
			</div>
			<hr style="border:1px solid black">
        </div>
    </div>
</div>