config/routes.rb
Rails.application.routes.draw do
  
  resources :regions do
    resources :places
  end
  
  resources :articles
  resources :categories
  resources :users_roles
  resources :roles
  resources :accounts

  get "/home/info" => "home#info", :as => :info
  post "/accounts/set_current_account/:id" => "accounts#set_current_account", :as => :set_current_account
  post "/accounts/set_state/:id" => "accounts#set_state", :as => :set_state
  post "/accounts/apply_account" => "accounts#apply_account", :as => :applyAccount

  root 'home#index'

  devise_for :users, controllers:{ registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :user

	has_many :preferences, :dependent => :destroy
	has_many :categories, through: :preferences

	after_create :save_categories
	after_update :update_categories

	def categories=(value)
		@categories = value
	end

	private

	def save_categories
		if @categories != nil
			@categories.each do |category_id|
				Preference.create(category_id: category_id, account_id: self.id)
			end
		end
	end

	def update_categories
		if @categories != nil
			Preference.where(account_id: self.id).destroy_all
			@categories.each do |category_id|
				Preference.create(category_id: category_id, account_id: self.id)
			end
		end
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	validates :title, presence: true
	validates :body, presence: true
	has_many :has_categories, :dependent => :destroy
	has_many :categories, through: :has_categories
	after_create :save_categories

	has_attached_file :cover #, styles: { large: "900x700", medium: "600x400", thumb: "500x300", small: "300x100" }
		#, :storage => :cloudinary, :path => ':id/:filename', :cloudinary_resource_type => :video
			#, :cloudinary_resource_type => :image 

	validates_attachment_content_type :cover,
		:content_type => ['video/mp4'],
		:message => "Sorry, right now we only support MP4 video",
		:if => :is_type_of_video?
	validates_attachment_content_type :cover,
		:content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'],
		:message => "Different error message",
		:if => :is_type_of_image?

	def categories=(value)
		@categories = value
	end

	protected

	def is_type_of_video?
		cover.content_type =~ %r(video)
	end

	def is_type_of_image?
		cover.content_type =~ %r(image)
	end


	private

	def save_categories
		@categories.each do |category_id|
			HasCategory.create(category_id: category_id, article_id: self.id)
		end
	end

end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true

	has_many :has_categories
	has_many :articles, through: :has_categories

	has_many :preferences
	has_many :accounts, through: :preferences

end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/place.rb
class Place < ApplicationRecord

	belongs_to :region

	has_attached_file :imagen , styles: { large: "900x700", medium: "600x400", thumb: "500x300", small: "300x100" }
	validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/

end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :account
  belongs_to :category
end

app/models/region.rb
class Region < ApplicationRecord
	has_attached_file :imagen , styles: { large: "900x700", medium: "600x400", thumb: "500x300", small: "300x100" }
	validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users_roles
	has_many :users, through: :users_roles

end

app/models/user.rb
class User < ApplicationRecord
	has_many :accounts, :dependent => :destroy
	has_many :users_roles, :dependent => :destroy
	has_many :roles, through: :users_roles

	after_create :set_role

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	def roles=(value)
		@roles = value
	end

	def set_role
		role = Role.find_by_name("subscribed")
		UsersRole.create(role_id: role.id, user_id: self.id)
		Account.create(user_id: self.id, role: role.name, state: "pending", location: "utp")
		UserMailer.notify_account(self).deliver
	end

end

app/models/users_role.rb
class UsersRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@last_articles ||= []
  	@categories = Category.all
  	@categories.each do |category|
  		@articles = category.articles
  		@last_articles.push(@articles.last)
  	end
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for(flash_type)
  case flash_type
  when "success"
    "alert-success"   # Green
  when "error"
    "alert-danger"    # Red
  when "alert"
    "alert-warning"   # Yellow
  when "notice"
    "alert-info"      # Blue
  else
    flash_type.to_s
  end
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_roles_helper.rb
module UsersRolesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', :back %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<!--p id="notice"><%= notice %></p-->
<div class="jumbotron sombra categorias">
	<h2 style="font-size: 50px; text-align: center; font-color: white"><%= @category.name %></h2>
</div>
<div class="container">
	<div class="row">
	<h4>Disfruta de increibles lugares</h4>
	<% if current_account.role == "admin" %>
		<h4><%= link_to "Nuevo artículo", new_article_path %></h4>
		<h4><%= link_to 'Editar categoria', edit_category_path(@category) %></h4>
	<%end%>
		<hr style="border:0.3px solid black">
	</div>
	<br>
	<% @category.articles.each do |article| %>
  <div class="row-md-4">
  	<div class="col-md-4">
      <div class="row" style="margin: 8px 8px 8px 8px;">
       	<%= article.cover.content_type %>
        <% if article.cover.content_type == 'video/mp4' || article.cover.content_type == 'application/octet-stream' %>
           	<%= video_tag article.cover.url(), class: "img-responsive", controls: true %>
        <% else %>
        	<%= image_tag article.cover.url(), class: "img-responsive" %>
        <%end%>
				<div class="caption">
		      <div class="breadcrumb" style="border: .3px solid grey;">
		          <h2 style="font-size: 20px"><%= article.title %></h2>
		          <h>Ubicación:  <%= article.location %></h>
		          <br>
		          <h>Categorias: </h>
		      	<% article.categories.each do |category| %>
		      		<%= link_to category.name, category%>
		      	<%end%>
		        <textarea disabled style="color:black; margin: 10px 0px 10px 0px" class="form-control"><%= article.body %></textarea>
		        <div class="row" style="margin-left: 2px">
			        <a class="btn btn-primary" href="#">Me gusta! <span class="glyphicon glyphicon-thumbs-up"></span>
			        </a>
			        <% if current_account.role == "admin" %>
			          <%= link_to 'Editar artículo', edit_article_path(article) %> ||
								<%= link_to 'Artículos', articles_path %>
							<%end%>
			      </div>
	        </div>
	        <hr style="border:0.3px solid black">
				</div>
			</div>
		</div>
  </div>
	<%end%>
	<br>
	<% if current_account.role == "admin" %>
		<% link_to 'Categorias', categories_path %>
	<%end%>
</div>