config/routes.rb
Rails.application.routes.draw do
  
  resources :regions do
    resources :places
  end
  
  resources :articles
  resources :categories
  resources :users_roles
  resources :roles
  resources :accounts

  get "/home/info" => "home#info", :as => :info
  post "/accounts/set_current_account/:id" => "accounts#set_current_account", :as => :set_current_account
  post "/accounts/set_state/:id" => "accounts#set_state", :as => :set_state
  post "/accounts/apply_account" => "accounts#apply_account", :as => :applyAccount

  root 'home#index'

  devise_for :users, controllers:{ registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :user

	has_many :preferences, :dependent => :destroy
	has_many :categories, through: :preferences

	after_create :save_categories
	after_update :update_categories

	def categories=(value)
		@categories = value
	end

	private

	def save_categories
		if @categories != nil
			@categories.each do |category_id|
				Preference.create(category_id: category_id, account_id: self.id)
			end
		end
	end

	def update_categories
		if @categories != nil
			Preference.where(account_id: self.id).destroy_all
			@categories.each do |category_id|
				Preference.create(category_id: category_id, account_id: self.id)
			end
		end
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	validates :title, presence: true
	validates :body, presence: true
	has_many :has_categories, :dependent => :destroy
	has_many :categories, through: :has_categories
	after_create :save_categories

	has_attached_file :cover #, styles: { large: "900x700", medium: "600x400", thumb: "500x300", small: "300x100" }
		#, :storage => :cloudinary, :path => ':id/:filename', :cloudinary_resource_type => :video
			#, :cloudinary_resource_type => :image 

	validates_attachment_content_type :cover,
		:content_type => ['video/mp4'],
		:message => "Sorry, right now we only support MP4 video",
		:if => :is_type_of_video?
	validates_attachment_content_type :cover,
		:content_type => ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'],
		:message => "Different error message",
		:if => :is_type_of_image?

	def categories=(value)
		@categories = value
	end

	protected

	def is_type_of_video?
		cover.content_type =~ %r(video)
	end

	def is_type_of_image?
		cover.content_type =~ %r(image)
	end


	private

	def save_categories
		@categories.each do |category_id|
			HasCategory.create(category_id: category_id, article_id: self.id)
		end
	end

end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true

	has_many :has_categories
	has_many :articles, through: :has_categories

	has_many :preferences
	has_many :accounts, through: :preferences

end

app/models/has_category.rb
class HasCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/place.rb
class Place < ApplicationRecord

	belongs_to :region

	has_attached_file :imagen , styles: { large: "900x700", medium: "600x400", thumb: "500x300", small: "300x100" }
	validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/

end

app/models/preference.rb
class Preference < ApplicationRecord
  belongs_to :account
  belongs_to :category
end

app/models/region.rb
class Region < ApplicationRecord
	has_attached_file :imagen , styles: { large: "900x700", medium: "600x400", thumb: "500x300", small: "300x100" }
	validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\Z/
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users_roles
	has_many :users, through: :users_roles

end

app/models/user.rb
class User < ApplicationRecord
	has_many :accounts, :dependent => :destroy
	has_many :users_roles, :dependent => :destroy
	has_many :roles, through: :users_roles

	after_create :set_role

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	def roles=(value)
		@roles = value
	end

	def set_role
		role = Role.find_by_name("subscribed")
		UsersRole.create(role_id: role.id, user_id: self.id)
		Account.create(user_id: self.id, role: role.name, state: "pending", location: "utp")
		UserMailer.notify_account(self).deliver
	end

end

app/models/users_role.rb
class UsersRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@last_articles ||= []
  	@categories = Category.all
  	@categories.each do |category|
  		@articles = category.articles
  		@last_articles.push(@articles.last)
  	end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    region = Region.find(params[:region_id])
    @places = region.places
    respond_to do |format|
      format.html
      format.xml { render :xml => @places}
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    region = Region.find(params[:region_id])
    @places = region.places.find(params[:id])
    respond_to do |format|
      format.html
      format.xml { render :xml => @places}
    end
    @place_articles ||= []
    @articles = Article.all
    @articles.each do |article|
      if article.location == @place.nombre
        @place_articles.push(article)
      end
    end
  end

  # GET /places/new
  def new
    region = Region.find(params[:region_id])
    @place = region.places.build
    respond_to do |format|
      format.html
      format.xml { render :xml => @places}
    end
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    region = Region.find(params[:region_id])
    #@place = region.places.create(params[:place])
    @place = region.places.create(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to [@place.region, @place], notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update

    region = Region.find(params[:region_id])
    @place = region.places.find(params[:id])

    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to [@place.region, @place], notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    region = Region.find(params[:region_id])
    @place = region.places.find(params[:id])
    @place.destroy
    respond_to do |format|
      format.html { redirect_to region_places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:nombre, :descripcion, :imagen)
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for(flash_type)
  case flash_type
  when "success"
    "alert-success"   # Green
  when "error"
    "alert-danger"    # Red
  when "alert"
    "alert-warning"   # Yellow
  when "notice"
    "alert-info"      # Blue
  else
    flash_type.to_s
  end
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_roles_helper.rb
module UsersRolesHelper
end

app/views/places/_form.html.erb
<div class="row">
  <div class="col-md-5 col-centered" align="left" style="font-size: 1.1em;">
    <%= bootstrap_form_for([@place.region, @place]) do |f| %>
      <% if @place.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

          <ul>
          <% @place.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :nombre, label: "Nombre", required: true %>
      </div>

      <div class="field">
        <%= f.text_area :descripcion, label: "Descripción", required: true, rows: "8" %>
      </div>

      <div class="field">
        <%= f.file_field :imagen, label: "Imagen", required: true %>
      </div>

      <div class="actions">
        <%= f.submit "Guardar", :class => 'btn btn-md btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/places/edit.html.erb
<h1>Editar lugar</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', [@place.region, @place] %> |
<%= link_to 'Back', region_places_path %>

app/views/places/index.html.erb
<!--p id="notice"><%= notice %></p-->
<div class="container">
  <h1>Lugares</h1>
  <%= link_to 'Nuevo lugar', new_region_place_path %>
  <br><br>
  <div class="row">
      <div class="col-md-12">
        <table class="table table-hover table-condensed table-bordered">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Descripcion</th>
              <!--th>Imagen</th-->
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @places.each do |place| %>
              <tr>
                <td><%= place.nombre %></td>
                <td><%= place.descripcion %></td>
                <!--td><%= place.imagen %></td-->
                <td><%= link_to 'Ver', [place.region, place] %></td>
                <td><%= link_to 'Editar', edit_region_place_path(place.region, place) %></td>
                <td><%= link_to 'Eliminar', [place.region, place], method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/places/new.html.erb
<div class="container">
	<h1>Nuevo lugar</h1>
	<%= render 'form', place: @place %>
	<br>
	<%= link_to 'Back', :back %>
</div>

app/views/places/show.html.erb
<!--p id="notice"><%= notice %></p-->
<div class="jumbotron sombra donde-ir">
  <h2 style="font-size: 50px; text-align: center; font-color: white"><%= @place.nombre %></h2>
  <h4 style="margin: -10px 0px 0px 0px; text-align: center"><%= link_to @place.region.nombre, @place.region %></h4>
</div>
<div class="container">
	<div class="row-md-5" style="text-align: left">
		<% if current_account.role == "admin" %>
			<h4><%= link_to "Nuevo Artículo", new_article_path %></h4>
		<%end%>
	</div>

	<div class="row-md-5">
		<%= image_tag @place.imagen.url(:medium), class: "img-responsive" %>
	</div>

	<div class="row-md-5" style="text-align: center">
	 	<ul class="breadcrumb">
			<h><%= @place.descripcion %></h>
		</ul>
	</div>

		<div>
			<% @place_articles.each do |article| %>
			<article >
				<header class="entry-header page-header">
					<hr class="section-divider" style="border:.8px solid black">
					<h2 class="entry-title"><%= article.title %></h2>
						<div class="entry-meta">
							<% article.categories.each do |category| %>
								<%= link_to category.name, category %>
							<%end%>
						</div><!-- .entry-meta -->
				</header><!-- .entry-header -->

				<div class="entry-content row">

					<div class="col-sm-6">
						<% if article.cover.content_type == 'video/mp4' || article.cover.content_type == 'application/octet-stream' %>
           	<%= video_tag article.cover.url(), class: "img-responsive", controls: true %>
		        <% else %>
		        	<%= image_tag article.cover.url(:thumb), class: "img-responsive" %>
		        <%end%>
					</div>

					<div class="col-sm-6">
						<h4><%= article.body %></h4>
					</div>
							
				</div><!-- .entry-content -->
				<%end%>
				<hr class="section-divider" style="border:.8px solid black">
			</article><!-- #post-## -->
		</div>

		<%= link_to 'Editar', edit_region_place_path(@place) %> |
		<%= link_to 'Atras', :back %>
	</div>
<br><br>
</div>