config/routes.rb
Rails.application.routes.draw do
  
  resources :regions do
    resources :places
  end
  
  resources :articles
  resources :categories
  resources :users_roles
  resources :roles
  resources :accounts

  get "/home/info" => "home#info", :as => :info
  post "/accounts/set_current_account/:id" => "accounts#set_current_account", :as => :set_current_account
  post "/accounts/set_state/:id" => "accounts#set_state", :as => :set_state
  post "/accounts/apply_account" => "accounts#apply_account", :as => :applyAccount

  root 'home#index'

  devise_for :users, controllers:{ registrations: 'users/registrations', sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :user

	has_many :preferences, :dependent => :destroy
	has_many :categories, through: :preferences

	after_create :save_categories
	after_update :update_categories

	def categories=(value)
		@categories = value
	end

	private

	def save_categories
		if @categories != nil
			@categories.each do |category_id|
				Preference.create(category_id: category_id, account_id: self.id)
			end
		end
	end

	def update_categories
		if @categories != nil
			Preference.where(account_id: self.id).destroy_all
			@categories.each do |category_id|
				Preference.create(category_id: category_id, account_id: self.id)
			end
		end
	end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
    @articles = Article.all
  end

  def set_current_account
    @account = Account.find(params[:id])
    current_user.accounts.each do |ac|
      if ac.id == @account.id
        ac.update_attribute(:state, "connected")
      else
        ac.update_attribute(:state, "active")
      end
    end
    redirect_to accounts_path
  end

  def set_state
    @account = Account.find(params[:id])
    if @account.state == "pending" or @account.state == "inactive"
      @account.update_attribute(:state, "active")
      UserMailer.notify_state(@account.user).deliver
    elsif @account.state == "active"
      @account.update_attribute(:state, "inactive")
    end
    redirect_to accounts_path
  end

  def apply_account
    if current_account.role == "subscribed"
      @account = Account.create(user_id: current_user.id, role: "admin",
         state: "pending", location: "utp")
    else
      if current_account.role == "admin"
        @account = Account.create(user_id: current_user.id, role: "root",
         state: "pending", location: "utp")
      end
    end
    redirect_to accounts_path
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @categories = Category.all
  end

  # GET /accounts/1/edit
  def edit
    @categories = Category.all
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account = current_user.accounts.new(account_params)
    @account.role = params[:role][:name]
    @account.categories = params[:categories]
    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      @account.categories = params[:categories]
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:role, :state, :category, :location, :categories)
    end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= bootstrap_form_for(account) do |f| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :role, disabled: true %>
  </div>

  <div class="field">
    <%= f.text_field :state, disabled: true %>
  </div>

  <div class="field">
    <%= f.text_field :location, disabled: false %>
  </div>

  <h2>Categorias</h2>
      <% @categories.each do |category| %>
      <div class="field">
        <%= check_box_tag "categories[]", category.id %> <%= category.name %>
      </div>
      <%end%>
  <br>

  <div class="actions">
    <%= f.submit "Actualizar cuenta", :class => 'btn btn-md btn-primary'%>
  </div>
  <br>
<% end %>

app/views/accounts/edit.html.erb
<div class="table-responsive container col-md-5">
	<h1>Editing Account</h1>

	<%= render 'form', account: @account %>

	<% link_to 'Mostrar', @account %> |
	<% link_to 'Cuentas', accounts_path %>
</div>

app/views/accounts/index.html.erb
<!--p id="notice"><%= notice %></p-->
<% if user_signed_in? %>
<div class="container">
  <ul class="breadcrumb">
    <h1>Mis cuentas</h1>
  </ul>
</div>
<div class="table-responsive container">
  <table class="table table-hover">
    <thead>
      <tr style="background:lightgrey">
        <th>Estado</th>
        <th>Rol</th>
        <th>Descripción</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <% if user_signed_in?%>
    <tbody>
      <% current_user.accounts.each do |ac| %>
        <tr>
          <% unless current_account.id == ac.id %>
            <% if ac.state == "active" %>
              <td><%= button_to 'Usar', set_current_account_path(ac.id), :class => 'btn btn-xs btn-success'%>
            <% elsif ac.state == "pending"%>
              <td><%= button_to 'Pendiente', current_account = ac , :class => 'btn btn-xs btn-warning',
              :disabled => true %>
            <% elsif ac.state == "inactive"%>
              <td><%= button_to 'Inactiva', current_account = ac , :class => 'btn btn-xs btn-warning',
              :disabled => true %>
            <%end%>
          <%else%>
            <td><%= button_to 'Usando', current_account = ac , :class => 'btn btn-xs btn-danger',
              :disabled => true %>
          <%end%>
          <td><%= ac.role %></td>

          <td><%= Role.find_by_name(ac.role).description %></td>
          <% unless current_user.accounts.find_by_role("admin") || current_account.role == "root" %>
            <td><%= button_to 'Aplicar para administrador', {:controller => "accounts", :action => "apply_account", :method=>:post }, :class => 'btn btn-xs btn-primary' %></td>
          <%end%>
          <td><%= link_to "Modificar preferencias", edit_account_path(ac) %></td>
        </tr>
      <% end %>
    </tbody>
  <%end%>
  </table>
  <br>
</div>
<hr style="border:1px solid black">
<% if current_account.role != "subscribed" %>
<div class="container">
  <ul class="breadcrumb">
    <h1>Cuentas administradas</h1>
  </ul>
</div>
<div class="table-responsive container">
  <table class="table table-hover">
    <thead>
      <tr style="background:lightgrey">
        <th>Usuario</th>
        <th>Rol</th>
        <!--th>Categoría</th-->
        <th>Ubicación</th>
        <th>Estado</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <tr>
        <% if current_account.role == "admin" and account.role == "subscribed"%>
          <td><%= account.user.email %></td>
          <td><%= account.role %></td>
          <!--td><%= account.role %></td-->
          <td><%= account.location %></td>
          <td><%= account.state %></td>
          <!--td><button class="btn btn-xs btn-success" onclick="window.location = '/accounts'">Allow</button></td-->
          <td><%= button_to 'Cambiar estado', set_state_path(account.id), :class => 'btn btn-xs btn-primary'%>
          <!--td><%= link_to 'Show', account %></td>
          <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
        <%else%>
          <% if current_account.role == "root" and account.role == "admin"%>
            <td><%= account.user.email %></td>
            <td><%= account.role %></td>
            <!--td><%= account.role %></td-->
            <td><%= account.location %></td>
            <td><%= account.state %></td>

            <td><%= button_to 'Cambiar estado', set_state_path(account.id), :class => 'btn btn-xs btn-primary'%>

            <!--td><%= link_to 'Edit', edit_account_path(account), class: "btn btn-xs btn -success" %></td-->
            <!--td><%= link_to 'Show', account %></td>
            <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
          <%end%>
        <%end%>
      <%end%>
        </tr>
    </tbody>
  </table>
  <br>
<% link_to 'New Account', new_account_path %>
</div>
<hr style="border:1px solid black">
<%end%>
<%end%>
<% if current_account.role == "admin" %>
  <% render "articles/admin" %>
<%end%>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<!--p id="notice"><%= notice %></p-->
<div class="container">
  <p class="h4">
    <strong>User:</strong>
    <%= @account.user.name %>
  </p>

  <p class="h4">
    <strong>Role:</strong>
    <%= @account.role %>
  </p>

  <p class="h4">
    <strong>State:</strong>
    <%= @account.state %>
  </p>

  <p class="h4">
    <strong>Category:</strong>
    <% @account.categories.each do |category| %>
      <%= link_to category.name, category %>
    <%end%>
  </p>

  <p class="h4">
    <strong>Location:</strong>
    <%= @account.location %>
  </p>

<% link_to 'Editar', edit_account_path(@account) %> 
<% link_to 'Cuentas', accounts_path %>
</div>

app/views/accounts/state.html.erb
<h1>Your account is in process of approval</h1>
<h2>will notify you when it is approved</h2>
<br><br>
<h1>Thank you!!</h1>